### ISSUE TITLE
[propose] how about to add cache from dns.lookup

### ISSUE THREAD

**Issue by my1229** [szmarczak/cacheable-lookup#37]
https://github.com/szmarczak/cacheable-lookup/blob/5960e1d98c61f9edd6873eb03050a12122f24af4/source/index.js#L330

this propose comes from my own experience when i'm using got client with cacheable-lookup cache in my node.js application:

> I found dns.resolve* always failed if i set the request host to k8s-service name (eg: my-service), i know the reason is calling c-ares in nodejs on the network and it seems about kube-dns not support this type of host, it will always return "NXDomain".
> 
> afterwards, cacheable-lookup use dns.lookup by getaddrinfo(3) in system (could search suffix from /etc/resolv.conf) and record it to _hostnamesToFallback(has 1h timeout), then my request will always use dns.lookup each time.  so the dns-cache feature is practically deprecated for my application unless the host is the whole k8s-service-name (like: my-service.svc.cluster.local).

Back to the propose, could we cache those dns from dns.lookup and add timeout to options? i think it is useful for node.js application in k8s-cluster and avoid some dns issues (like: lookup timeout) in high concurrency scenarios.

**Comment by szmarczak** [comment]
The current solution is still pretty fast. I'm getting 20-30k op/s with ~15-20% of CPU.

This is not going to work; IPs can change when a container is restarted. So that would invalidate the cache - but cache itself doesn't know if it's valid or not. Therefore I decided to make it default to `lookup`.

> lookup timeout

There is no lookup timeout when you query a hostname that is defined by your OS.

If you want to be really fast, you don't need to use cache at all. Just set static IPs on your containers and provide the `host` option - that way there is no lookup.
